language: csharp
solution: PI_Travisci.sln  
sudo: required  
dist: trusty  
mono: none
dotnet: 2.0.0
before_script:
  - dotnet restore
script:  
  - dotnet build ./PI_Travisci.sln -c Release -f netcoreapp2.0 